//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Message
{

    protected virtual string messageType;

    protected virtual string messageID;

    protected virtual int maxMessageLength;

    public virtual WriteToFile WriteToFile;

    public virtual string getMessageType()
    {
        throw new System.NotImplementedException();
    }

    public virtual void setMessageType()
    {
        throw new System.NotImplementedException();
    }

    public virtual string getMessageID()
    {
        throw new System.NotImplementedException();
    }

    public virtual void setMessageID()
    {

    }
    public virtual void printMessage()
    {
        throw new System.NotImplementedException();
    }

    public virtual int getMaxMessageLength()
    {
        throw new System.NotImplementedException();
    }

    public virtual void setMaxMessageLength()
    {
        throw new System.NotImplementedException();
    }

    public virtual void Sender()
    {
        throw new System.NotImplementedException();
    }

}


