//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SignificantIncedentReports : Email
{
    private string sortCode;
    private string natureOfIncedent;

    public virtual void writeToSIRList()
    {

    }

    //getters and setters for sort code
	public string getSortCode()
	{
        return this.sortCode;
	}

	public virtual void setSortCode(string sortCode)
	{
        this.sortCode = sortCode;
	}

    //getters and setters for the Nature Of Incedent (NOI)
	public virtual string getNOI()
	{
        return this.natureOfIncedent;
	}

	public virtual void setNOI(string noi)
	{
        this.natureOfIncedent = noi;
	}

    

    
}

