//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

public class SMS : Message
{
    List<string> abbrevs = new List<string>();

    public SMS()
    {
        using (StreamReader r = new StreamReader("textwords.csv"))
        {
            String line;

            while ((line = r.ReadLine()) != null)
            {
                abbrevs.Add(line);
            }
        }
    }

    public String textSpeakAbbrevations(string message)
    {
        foreach (string s in abbrevs)
        {
            string a = s.Substring(0, s.IndexOf(","));
            string b = s.Substring(s.IndexOf(",") + 1, s.Length - s.IndexOf(",") - 1);

            if(message.Contains(a))
            {
                message = message.Insert(message.IndexOf(a) + a.Length, "<"+b+">");
            }
        }

        return message;

    }

    //returning the message length of 140 for if sender type is SMS
    public override int getMaxMessageLength()
    {
        return 140;
    }


}

